### ISSUE TITLE
Action Taimanin 

### ISSUE THREAD

**Issue by AH800** [sst311212/FuckBootStrap#1]
obbassit in action taimanin its broken

**Comment by sst311212** [comment]
This project is not work anymore after game updated unity engine, that's why it archived.
And also, mod author said he will not update mod in the future.

**Comment by sst311212** [comment]
> obbassit in action taimanin its broken

Good news, the mod is working again.

**Comment by nckkel** [comment]
> > obbassit in action taimanin its broken
> 
> Good news, the mod is working again.

How can I use it?
